apiVersion: apps/v1
kind: Deployment
metadata:
  name: techfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techfood-app
  template:
    metadata:
      labels:
        app: techfood-app
    spec:
      containers:
        - name: techfood-app
          image: pcantarelli/techfood
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SPRING_DATASOURCE_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
